image: cirrusci/flutter:2.0.4

stages:
  - test

before_script:
  - flutter pub get
  - flutter pub run build_runner build --delete-conflicting-outputs
  - flutter pub global activate pubspec_version
  - flutter pub global activate intl_utils
  - flutter pub global run intl_utils:generate
  - FLUTTER_VERSION=`flutter pub global run pubspec_version:pubver get`
  - export BUILD_VERSION=$(echo $FLUTTER_VERSION | cut -d "+" -f1)
  - export BUILD_NUMBER=$(echo $FLUTTER_VERSION | cut -d "+" -f2)
  - export BUILD_NUMBER=$CI_PIPELINE_IID
  - echo Build Version $BUILD_VERSION
  - echo Build Number $BUILD_NUMBER
  - mkdir $CI_PROJECT_DIR/android/app/src/production
  - echo $B64_GOOGLE_SERVICES_JSON  | base64 --decode > $CI_PROJECT_DIR/android/app/src/production/google-services.json
  - if [ -n "$B64_KEYSTORE_PROPERTIES" ]; then echo $B64_KEYSTORE_PROPERTIES | base64 --decode > $CI_PROJECT_DIR/android/app/keystore.properties; fi
  - if [ -n "$B64_KEYSTORE" ]; then echo $B64_KEYSTORE | base64 --decode > $CI_PROJECT_DIR/android/app/master.keystore; fi

test:
  stage: test
  when: always
  script:
    - flutter analyze
    - flutter test --coverage
  only:
    - /^bugfix/.*$/
    - /^feature/.*$/
    - /^epic/.*$/
    - /^hotfix/.*$/
    - develop
