image: cirrusci/flutter:stable

stages:
  - test
  - build

before_script:
  - flutter pub get
  - flutter pub run build_runner build --delete-conflicting-outputs
  - flutter pub global activate pubspec_version
  - flutter pub global activate intl_utils
  - flutter pub global run intl_utils:generate

test:
  stage: test
  when: always
  tags:
    - flutter_build
  script:
    - flutter analyze
    - flutter test --coverage
  only:
    - /^bugfix/.*$/
    - /^feature/.*$/
    - /^epic/.*$/
    - /^hotfix/.*$/
    - develop

build_android_dev: #Job name
  stage: build # kind of job
  when: always
  script:
    - flutter build apk --flavor development
  artifacts:
    paths:
      - build/app/outputs/apk/release/app-release.apk
  tags:
    - flutter_build
  only:
    - /^bugfix/.*$/
    - /^feature/.*$/
    - /^epic/.*$/
    - /^hotfix/.*$/
    - develop