image: cirrusci/flutter:stable

stages:
  - test

before_script:
  - flutter pub get
  - flutter pub run build_runner build --delete-conflicting-outputs
  - flutter pub global activate pubspec_version
  - flutter pub global activate intl_utils
  - flutter pub global run intl_utils:generate

test:
  stage: test
  when: always
  tags:
    - flutter_build
  script:
    - flutter analyze
    - flutter test --coverage
  only:
    - /^bugfix/.*$/
    - /^feature/.*$/
    - /^epic/.*$/
    - /^hotfix/.*$/
    - develop
